name: 'nimpretty-action'
description: 'Nimpretty GitHub Action'
inputs:
  folders:
    description: 'Folders to start recursive walking from'
    required: false
    default: ['.']
  indent:
    description: '--indent'
    required: false
    default: 2
  maxLineLen:
    description: '--maxLineLen'
    required: false
    default: 999  # Conservative because some people use long lines (Regex, etc).
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'eye'
  color: 'yellow'
