on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.0'


      - name: nimpretty
        uses: juancarlospaco/nimpretty-action@main
        with:
            folder: "."
            filter: "/\.nim$/"
